ALTER TABLE leads
    ADD COLUMN IF NOT EXISTS user_id BIGINT NULL;

ALTER TABLE leads
    ADD CONSTRAINT fk_leads_user FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE blueprints
    ADD COLUMN IF NOT EXISTS client_email VARCHAR(320) NULL;
